# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LYSKitSDKTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LYSKitSDKTest
pod 'ReactiveCocoa', '~> 7.0.1'
end
